/// Asset path constants for MathMate.
///
/// All image asset paths are centralized here to:
/// - Avoid typos in asset path strings
/// - Provide autocomplete in the IDE
/// - Make it easy to find all assets used in the app
///
/// Flutter resolves resolution variants automatically.
/// When you reference `assets/images/empty_history.png`, Flutter
/// loads the 2.0x or 3.0x variant based on the device pixel ratio.
///
/// Usage:
/// ```dart
/// Image.asset(AppAssets.emptyHistory, width: 120, height: 120)
/// ```
abstract class AppAssets {
  /// Base path for image assets.
  static const String _imagesBase = 'assets/images';

  /// Placeholder image for the empty history state.
  ///
  /// Shows a clock with a diagonal slash, conveying "no history yet."
  /// Generated by `tool/generate_placeholder_images.dart`.
  static const String emptyHistory = '$_imagesBase/empty_history.png';
}
